/* -LICENSE-START-
** Copyright (c) 2011 Blackmagic Design
**
** Permission is hereby granted, free of charge, to any person or organization
** obtaining a copy of the software and accompanying documentation covered by
** this license (the "Software") to use, reproduce, display, distribute,
** execute, and transmit the Software, and to prepare derivative works of the
** Software, and to permit third-parties to whom the Software is furnished to
** do so, all subject to the following:
** 
** The copyright notices in the Software and this entire statement, including
** the above license grant, this restriction and the following disclaimer,
** must be included in all copies of the Software, in whole or in part, and
** all derivative works of the Software, unless such copies or derivative
** works are solely in the form of machine-executable object code generated by
** a source language processor.
** 
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
** DEALINGS IN THE SOFTWARE.
** -LICENSE-END-
*/
#pragma once
#include <iostream>
//#include "stdafx.h"
#include "AtemControl.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif


// User defined messages for signalling callback results to main thread
#define WM_MIX_EFFECT_BLOCK_PROGRAM_INPUT_CHANGED				WM_USER+1
#define WM_MIX_EFFECT_BLOCK_PREVIEW_INPUT_CHANGED				WM_USER+2
#define WM_MIX_EFFECT_BLOCK_IN_TRANSITION_CHANGED				WM_USER+3
#define WM_MIX_EFFECT_BLOCK_TRANSITION_POSITION_CHANGED			WM_USER+4
#define WM_MIX_EFFECT_BLOCK_TRANSITION_FRAMES_REMAINING_CHANGED	WM_USER+5
#define WM_MIX_EFFECT_BLOCK_FTB_FRAMES_REMAINING_CHANGED		WM_USER+6
#define WM_SWITCHER_INPUT_LONGNAME_CHANGED						WM_USER+7
#define WM_SWITCHER_DISCONNECTED								WM_USER+8

// Callback class for monitoring property changes on a mix effect block.
class MixEffectBlockMonitor : public IBMDSwitcherMixEffectBlockCallback
{
public:
	MixEffectBlockMonitor() :mRefCount(1) { }

protected:
	virtual ~MixEffectBlockMonitor() { }

public:
	HRESULT STDMETHODCALLTYPE QueryInterface(REFIID iid, LPVOID *ppv)
	{
		if (!ppv)
			return E_POINTER;

		if (IsEqualGUID(iid, IID_IBMDSwitcherMixEffectBlockCallback))
		{
			*ppv = static_cast<IBMDSwitcherMixEffectBlockCallback*>(this);
			AddRef();
			return S_OK;
		}

		if (IsEqualGUID(iid, IID_IUnknown))
		{
			*ppv = static_cast<IUnknown*>(this);
			AddRef();
			return S_OK;
		}

		*ppv = NULL;
		return E_NOINTERFACE;
	}

	ULONG STDMETHODCALLTYPE AddRef(void)
	{
		return InterlockedIncrement(&mRefCount);
	}

	ULONG STDMETHODCALLTYPE Release(void)
	{
		int newCount = InterlockedDecrement(&mRefCount);
		if (newCount == 0)
			delete this;
		return newCount;
	}

	HRESULT STDMETHODCALLTYPE Notify(BMDSwitcherMixEffectBlockEventType eventType)
	{
		switch (eventType)
		{
			case bmdSwitcherMixEffectBlockEventTypeProgramInputChanged:
				//PostMessage(mHwnd, WM_MIX_EFFECT_BLOCK_PROGRAM_INPUT_CHANGED, 0, 0);
				break;
			case bmdSwitcherMixEffectBlockEventTypePreviewInputChanged:
				//PostMessage(mHwnd, WM_MIX_EFFECT_BLOCK_PREVIEW_INPUT_CHANGED, 0, 0);
				break;
			case bmdSwitcherMixEffectBlockEventTypeInTransitionChanged:
				//PostMessage(mHwnd, WM_MIX_EFFECT_BLOCK_IN_TRANSITION_CHANGED, 0, 0);
				break;
			case bmdSwitcherMixEffectBlockEventTypeTransitionPositionChanged:
				//PostMessage(mHwnd, WM_MIX_EFFECT_BLOCK_TRANSITION_POSITION_CHANGED, 0, 0);
				break;
			case bmdSwitcherMixEffectBlockEventTypeTransitionFramesRemainingChanged:
				//PostMessage(mHwnd, WM_MIX_EFFECT_BLOCK_TRANSITION_FRAMES_REMAINING_CHANGED, 0, 0);
				break;
			case bmdSwitcherMixEffectBlockEventTypeFadeToBlackFramesRemainingChanged:
				//PostMessage(mHwnd, WM_MIX_EFFECT_BLOCK_FTB_FRAMES_REMAINING_CHANGED, 0, 0);
				break;
			default:	// ignore other property changes not used for this sample app
				break;
		}
		return S_OK;
	}

private:
	//HWND		mHwnd;
	LONG		mRefCount;
};

// Monitor the properties on Switcher Inputs.
// In this sample app we're only interested in changes to the Long Name property to update the PopupButton list
class InputMonitor : public IBMDSwitcherInputCallback
{
public:
	InputMonitor(IBMDSwitcherInput* input) : mInput(input), mRefCount(1)
	{
		mInput->AddRef();
		mInput->AddCallback(this);
	}

protected:
	~InputMonitor()
	{
		mInput->Release();
	}

public:
	void RemoveCallback(void) { mInput->RemoveCallback(this); }

	// IBMDSwitcherInputCallback interface
	HRESULT STDMETHODCALLTYPE QueryInterface(REFIID iid, LPVOID *ppv)
	{
		if (!ppv)
			return E_POINTER;

		if (IsEqualGUID(iid, IID_IBMDSwitcherInputCallback))
		{
			*ppv = static_cast<IBMDSwitcherInputCallback*>(this);
			AddRef();
			return S_OK;
		}

		if (IsEqualGUID(iid, IID_IUnknown))
		{
			*ppv = static_cast<IUnknown*>(this);
			AddRef();
			return S_OK;
		}

		*ppv = NULL;
		return E_NOINTERFACE;
	}

	ULONG STDMETHODCALLTYPE AddRef(void)
	{
		return InterlockedIncrement(&mRefCount);
	}

	ULONG STDMETHODCALLTYPE Release(void)
	{
		int newCount = InterlockedDecrement(&mRefCount);
		if (newCount == 0)
			delete this;
		return newCount;
	}

	HRESULT STDMETHODCALLTYPE Notify(BMDSwitcherInputEventType eventType)
	{
		switch (eventType)
		{
			case bmdSwitcherInputEventTypeLongNameChanged:
				//PostMessage(mHwnd, WM_SWITCHER_INPUT_LONGNAME_CHANGED, 0, 0);
				break;
			default:	// ignore other property changes not used for this sample app
				break;
		}
		return S_OK;
	}
	IBMDSwitcherInput* input() { return mInput; }

private:
	IBMDSwitcherInput*		mInput;
	//HWND					mHwnd;
	LONG					mRefCount;
};

// Callback class to monitor switcher disconnection
class SwitcherMonitor : public IBMDSwitcherCallback
{
public:
	SwitcherMonitor() :mRefCount(1) { }

protected:
	virtual ~SwitcherMonitor() { }

public:
	// IBMDSwitcherCallback interface
	HRESULT STDMETHODCALLTYPE QueryInterface(REFIID iid, LPVOID *ppv)
	{
		if (!ppv)
			return E_POINTER;

		if (IsEqualGUID(iid, IID_IBMDSwitcherCallback))
		{
			*ppv = static_cast<IBMDSwitcherCallback*>(this);
			AddRef();
			return S_OK;
		}

		if (IsEqualGUID(iid, IID_IUnknown))
		{
			*ppv = static_cast<IUnknown*>(this);
			AddRef();
			return S_OK;
		}

		*ppv = NULL;
		return E_NOINTERFACE;
	}

	ULONG STDMETHODCALLTYPE AddRef(void)
	{
		return InterlockedIncrement(&mRefCount);
	}

	ULONG STDMETHODCALLTYPE Release(void)
	{
		int newCount = InterlockedDecrement(&mRefCount);
		if (newCount == 0)
			delete this;
		return newCount;
	}

	// Switcher event callback
	HRESULT STDMETHODCALLTYPE	Notify(BMDSwitcherEventType eventType, BMDSwitcherVideoMode coreVideoMode)
	{
		//if (eventType == bmdSwitcherEventTypeDisconnected)
		{
			//PostMessage(mHwnd, WM_SWITCHER_DISCONNECTED, 0, 0);
		}
		
		return S_OK;
	}

private:
	//HWND	mHwnd;
	LONG	mRefCount;
};


// CSwitcherPanelDlg dialog


// CSwitcherPanelDlg message handlers

AtemControl::AtemControl()
{


	// Initialize COM and Switcher related members
	if (FAILED(CoInitialize(NULL)))
	{
		//MessageBox(_T("CoInitialize failed."), _T("Error"));
		//goto bail;
	}

	mSwitcherDiscovery = NULL;
	mSwitcher = NULL;
	mMixEffectBlock = NULL;

	//mSwitcherMonitor = new SwitcherMonitor();
	//mMixEffectBlockMonitor = new MixEffectBlockMonitor();

	mMoveSliderDownwards = FALSE;
	mCurrentTransitionReachedHalfway = FALSE;

	mSwitcherDiscovery = NULL;
	HRESULT hr = CoCreateInstance(CLSID_CBMDSwitcherDiscovery, NULL, CLSCTX_ALL, IID_IBMDSwitcherDiscovery, (void**)&mSwitcherDiscovery);
	if (FAILED(hr))
	{
		printf("Could not create Switcher Discovery Instance.\nATEM Switcher Software may not be installed.");
		//goto bail;
	}

	switcherDisconnected();		// start with switcher disconnected

	//return TRUE;				// return TRUE unless you set the focus to a control

//bail:
	//return FALSE;
}

HRESULT AtemControl::Connect(CString _address)
{
	BMDSwitcherConnectToFailure			failReason;
	//CString address;

	//mEditAddress.GetWindowText(address);
	BSTR addressBstr = _address.AllocSysString();

	// Note that ConnectTo() can take several seconds to return, both for success or failure,
	// depending upon hostname resolution and network response times, so it may be best to
	// do this in a separate thread to prevent the main GUI thread blocking.
	HRESULT hr = mSwitcherDiscovery->ConnectTo(addressBstr, &mSwitcher, &failReason);
	SysFreeString(addressBstr);
	if (SUCCEEDED(hr))
	{
		switcherConnected();
	}
	else
	{
		switch (failReason)
		{
			case bmdSwitcherConnectToFailureNoResponse:
				printf("No response from Switcher"), _T("Error");
				break;
			case bmdSwitcherConnectToFailureIncompatibleFirmware:
				printf("Switcher has incompatible firmware"), _T("Error");
				break;
			default:
				printf("Connection failed for unknown reason"), _T("Error");
				break;
		}
	}

	return hr;
}

HRESULT AtemControl::Auto()
{
	return mMixEffectBlock->PerformAutoTransition();
}

HRESULT AtemControl::Cut()
{
	return mMixEffectBlock->PerformCut();
}

HRESULT AtemControl::FTB()
{
	return mMixEffectBlock->PerformFadeToBlack();
}


HRESULT AtemControl::switcherConnected()
{
	HRESULT result;
	IBMDSwitcherMixEffectBlockIterator* iterator = NULL;
	IBMDSwitcherInputIterator* inputIterator = NULL;

	BSTR productName;
	if (FAILED(mSwitcher->GetProductName(&productName)))
	{
		printf("Could not get switcher product name");
		return E_FAIL;
	}
	CString productNameCString(productName);
	SysFreeString(productName);
	mProductName = productName;
	//std::cout << productNameCString +"\n";

	mMixerConnected = TRUE;

	//printf(productNameCString);
	//mEditName.SetWindowText(productNameCString);

	//mSwitcher->AddCallback(mSwitcherMonitor);

	// Create an InputMonitor for each input so we can catch any changes to input names
	result = mSwitcher->CreateIterator(IID_IBMDSwitcherInputIterator, (void**)&inputIterator);
	if (SUCCEEDED(result))
	{
		IBMDSwitcherInput* input = NULL;

		// For every input, install a callback to monitor property changes on the input
		while (S_OK == inputIterator->Next(&input))
		{
			//InputMonitor* inputMonitor = new InputMonitor(input);
			//input->Release();
			//mInputMonitors.push_back(inputMonitor);
		}
		inputIterator->Release();
		inputIterator = NULL;
	}

	// Get the mix effect block iterator
	result = mSwitcher->CreateIterator(IID_IBMDSwitcherMixEffectBlockIterator, (void**)&iterator);
	if (FAILED(result))
	{
		printf("Could not create IBMDSwitcherMixEffectBlockIterator iterator");
		//goto finish;
	}

	// Use the first Mix Effect Block
	if (S_OK != iterator->Next(&mMixEffectBlock))
	{
		printf("Could not get the first IBMDSwitcherMixEffectBlock");
		//goto finish;
	}

	//mMixEffectBlock->AddCallback(mMixEffectBlockMonitor);

	return result;
//finish:
	//if (iterator)
	//	iterator->Release();
}

void AtemControl::switcherDisconnected()
{
	//mButtonConnect.EnableWindow(TRUE);		// enable connect button so user can re-connect
	//mEditName.SetWindowText(_T(""));

	//mixEffectBlockBoxSetEnabled(FALSE);

	// cleanup resources created when switcher was connected
	for (std::list<InputMonitor*>::iterator it = mInputMonitors.begin(); it != mInputMonitors.end(); ++it)
	{
		(*it)->RemoveCallback();
		(*it)->Release();
	}
	mInputMonitors.clear();

	if (mMixEffectBlock)
	{
		mMixEffectBlock->RemoveCallback(mMixEffectBlockMonitor);
		mMixEffectBlock->Release();
		mMixEffectBlock = NULL;
	}

	if (mSwitcher)
	{
		mSwitcher->RemoveCallback(mSwitcherMonitor);
		mSwitcher->Release();
		mSwitcher = NULL;
	}
}

string AtemControl::GetProductName()
{
	if(mMixerConnected)
	{

	std::wstring wideName = wstring(mProductName);
	std::string MixerName( wideName.begin(), wideName.end() );
	
	return MixerName;
	
	}
	else{
		return "Atem Not Connected";
	}
}


void AtemControl::OnClose()
{
	switcherDisconnected();

	if (mSwitcherMonitor != NULL)
	{
		mSwitcherMonitor->Release();
		mSwitcherMonitor = NULL;
	}

	if (mMixEffectBlockMonitor != NULL)
	{
		mMixEffectBlockMonitor->Release();
		mMixEffectBlockMonitor = NULL;
	}

	if (mSwitcherDiscovery != NULL)
	{
		mSwitcherDiscovery->Release();
		mSwitcherDiscovery = NULL;
	}

	CoUninitialize();

	//CDialog::OnClose();
}


